### ISSUE TITLE
LEDs not coming on

### ISSUE THREAD

**Issue by sauceboss43** [srg74/WLED-ESP32-dev-board#1]
I just got my WLED-ESP32-universal-contoller in and connected it up but am not getting any lights to come on but I believe I have set everything up correctly. I can turn the board on and off and can hear the relay click and have confirmed that 5V is at either side of the stip. I then looked at the data pin and found I was getting a voltage going to the first LED, from D1 data pin, but the voltage is not passed on after the first LED. The first LED was lighting up at one point but now it does not even turn on. Here is my config in the wled app:
![image](https://user-images.githubusercontent.com/111309715/190043468-b09c7e7a-14c6-4838-acb8-013a66b86bca.png)
![image](https://user-images.githubusercontent.com/111309715/190043737-d2a43bf3-93c4-4aa3-b31f-7fe0ec2187f8.png)

Any help would be appreciated. I have tried two different LED strips with the same results. Sorry if this is something easy I am just missing, this is my first attempt at this! Thaknks!

**Comment by blazoncek** [comment]
You need to connect LED2 output if you use GPIO2 or change GPIO to 1 if you want LED1 output.

**Comment by sauceboss43** [comment]
So it was something obvious I was just missing, that fixed it! Thanks for the help, much appreciated!
