### ISSUE TITLE
No current

### ISSUE THREAD

**Issue by ChristianLus** [srg74/WLED-ESP32-dev-board#3]
I'm unable to light up my LED strip. I am using a SK6812RGBW strip with 150 LEDs

I also have a 5V 20A power supply that I connected to the PWR and G of the board. These pins do not seem to power the board itself so I am currently powering the controller through micro USB from a computer. 

I have WLED loaded and connected but I'm not seeing any current leaving the terminals of the board at all. I'm not great with electronics but I tried testing between the 5V power terminal and the ground and there's nothing coming out for the LED strip. 

Do you have any suggestions? I can add any additional information that may be helpful.

**Comment by srg74** [comment]
Please move to WLED discord my nick is @Serg5959 https://discord.gg/KuqP7NE
